#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create a virtual environment
#
# If you're using vscode, this is where the venv lives that it will
# call by default.
export VENV=/home/vscode/.local/ha-venv
#
# If you're running closer to the metal, you might prefer this
# instead:
# export VENV=venv

# Hopefully prioritise finding bermuda sources in our
# working dir while debugging, rather than in the HA tree.
export PYTHONPATH="${PWD}/custom_components:${PYTHONPATH}"

python3 -m venv $VENV
source $VENV/bin/activate

# Seems to fix broken aiohttp wheel building in 3.11:
uv pip install --upgrade setuptools wheel
# Fix urllib3 issue https://github.com/home-assistant/core/issues/95192
uv pip install git+https://github.com/boto/botocore

uv pip install --requirement requirements.txt
uv pip install --requirement requirements_test.txt
