#!/bin/bash

# Create a virtual environment
#python3 -m venv venv
#source venv/bin/activate
# Install requirements
pip install -r requirements_test.txt
# Run tests and get a summary of successes/failures and code coverage
pytest --durations=10 --cov-report term-missing --cov=custom_components.bermuda tests
