name: Draft a release note
on:
  push:
    # Defaults to all.
    branches:
      - main
      - develop
      - testing
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
    # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # write on pr's is required for autolabeller
      pull-requests: write
    outputs:
      resolved_version: ${{ steps.draftrelease.outputs.resolved_version }}
    steps:
      - name: Run release-drafter
        id: draftrelease
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
